---
title: "PROB_ML"
output: html_document
---

```{r}

library(ggplot2)
library(dplyr)
library(xtable)
library(brms)
library(pscl)
library(MASS)
library(lme4)
library(readr)
library(AER)
library(rpart)
library(mlbench)
library(GGally)

```


```{r create_data}
data <- read_csv("code/meta_data_citations.csv")

data$publish_time_new = as.Date(data$publish_time)

data$pub_year <- (ifelse(is.na(data$publish_time_new),as.numeric(data$publish_time),as.numeric(format(data$publish_time_new,'%Y')))-2020)*-1


#encoding = "datasets/full_data.csv"
encoding = "datasets/isomap_full_data.csv"
#encoding = "datasets/meta_data_citations.csv"

full_data <- read_csv(encoding, 
     col_names = FALSE)

full_data =full_data %>% 
  rename(
    pmcid = X1,
    date = X2,
    journal = X3,
    citations = X4,
    references = X5,
    abs_closest = X6,
    abs_close6 = X7,
    abs_close_count = X8,
    abstract1 = X9,
    abstract2 = X10,
    abstract3 = X11,
    abstract4 = X12,
    abstract5 = X13,
    doc_closest = X14,
    doc_close6 = X15,
    doc_close_count = X16,
    doc1 = X17,
    doc2 = X18,
    doc3 = X19,
    doc4 = X20,
    doc5 = X21
    )%>%
  mutate(log_citations = log(citations+0.01))

year = data[,c("pmcid","pub_year")]
dat = train %>%group_by(journal) %>% summarize(jrnl_ct = n()) %>% arrange()

full_data_merge = merge(full_data, year, by = "pmcid")
full_data_merge = merge(full_data_merge, dat, by = "journal")

full_data_merge = full_data_merge %>% mutate(
  journal = ifelse(jrnl_ct>20,journal, "other")
)

plot(log(train$references), train$log_citations)
plot(log(train$abs_closest), train$log_citations)
plot(log(train$abs_close6), train$log_citations)
plot((train$abs_close_count), train$log_citations)

ggplot(data = train, aes(x=abs_close_count, y = log_citations))+
  geom_point()

modellm = lm(data = train, log_citations ~log(abs_closest)+log(abs_close6)+abs_close_count)
summary(modellm)

modelm2 = lm(data = train, log_citations ~log(abs_closest)+log(abs_close6)+abs_close_count+abstract3+abstract4+abstract5+log(doc_closest+1)+doc_close6+log(doc2^2)+log(doc3^2)+pub_year+journal)
summary(modelm2)




```


```{r linear models}
summary(full_data_merge)

model_data = full_data_merge %>% dplyr::select(-date,-pmcid) %>% filter(pub_year !=0)

pred_data = full_data_merge %>% filter(pub_year==0)

set.seed(123)
train_ind <- sample(seq_len(nrow(model_data)), size = nrow(model_data)*.6)

train <- model_data[train_ind, ]
test <- model_data[-train_ind, ]



model1 = lm(data = train, log_citations~.-citations-journal)


plot(model1)
summary(model1)

mean(model1$residuals^2)

model1.2 = glm(data = train, log_citations~.-citations-journal)
summary(model1.2)


model2 = glm(data = train, citations~.-log_citations-journal, family = "poisson")
summary(model2)

model2.2 = glm(data = train, citations~.-log_citations-journal, family = "quasipoisson")
summary(model2.2)


#does not converge
model3 = glm.nb(citations ~.-journal-log_citations , data = train)
summary(model3)


```


```{r trees}

tree1 = rpart(log_citations~.-citations, data=train, method='anova',control=rpart.control(minsplit=10)) 

rsq.rpart(tree1)

printcp(tree1)


tree2 = rpart(high_cit~.-citations-log_citations, data=train1, method='class',control=rpart.control(minsplit=10)) 

rsq.rpart(tree2)

printcp(tree2)
```

```{r}
# Random Forest prediction of Kyphosis data
library(randomForest)
traina = na.omit(train)
fit <- randomForest(citations ~ . -log_citations-journal,   data=traina)
print(fit) # view results
importance(fit) # importance of each predictor

summary(traina)


zinb <- zeroinfl(formula=citations ~ .-log_citations-journal|1,
                 dist="poisson",
                 data=train,trace=TRUE)

zinbin <- zeroinfl(formula=citations ~ .-log_citations-journal|1,
                 dist="negbin",
                 data=train,trace=TRUE)

zinb_all <- zeroinfl(formula=citations ~ .-log_citations-journal|.-log_citations-journal,
                 dist="poisson",
                 data=train,trace=TRUE)

zinbin_all <- zeroinfl(formula=citations ~ .-log_citations-journal|.-log_citations-journal,
                 dist="negbin",
                 data=train,trace=TRUE)


```


```{r}
hist (full_data_merge$citations)
hist (full_data_merge$log_citations)

library(gridExtra)
l = ggplot(data = full_data_merge)+
  geom_histogram(aes(x = citations))+
  theme_bw(base_size = 4)+
  theme(text=element_text(family="Times New Roman"))+
  xlab("Citation Count")+ylab("Count")

lc = ggplot(data = full_data_merge)+
  geom_histogram(aes(x = log_citations))+
  theme_bw(base_size = 4)+
  theme(text=element_text(family="Times New Roman"))+
  xlab("Log(Citation Count+1)")+ylab("Count")

grid.arrange(l, lc, nrow = 1)

g = (arrangeGrob(l,lc,nrow = 1))


ggsave("Figures/citation_hist.png", plot = g, width = 1.5, height = .7,dpi = 320)
```

